version: '3.8'

services:
  auth-app:
    image: authentication:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Different port to avoid conflict with inventory service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth_mysql:3306/auth_db?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_PLATFORM=mysql
      - SPRING_APPLICATION_NAME=authentication
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql-network

  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=auth_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    ports:
      - "3307:3306" # Different port to avoid conflict with other MySQL instances
    networks:
      - mysql-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  mysql-network:
    name: auth_app-network
    external: true